name: Build libFMS with cmake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        omp-flags: [ -DOPENMP=on, -DOPENMP=off ]
    container:
      image: ghcr.io/noaa-gfdl/fms/fms-ci-rocky-gnu:15.1.0
      env:
        CMAKE_FLAGS: "${{ matrix.omp-flags }} -D64BIT=on"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate makefiles with CMake
      run: cmake $CMAKE_FLAGS .
    - name: Build the library
      run: make
