name: Linux verification

on: [push, pull_request, workflow_dispatch]

jobs:
  # Documentation

  check-style-and-docstrings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Check white space (non-blocking)
      run: |
        ./.testing/trailer.py -e TEOS10 -l 120 tim 2>&1 | tee style_errors
      continue-on-error: true

